/** Persistence boundary for the bounded Jira board demo. */
import {
  neon,
  type NeonQueryFunction,
  type NeonQueryFunctionInTransaction,
} from "@neondatabase/serverless";

export type DemoBoardType = "kanban" | "scrum" | "simple";

export type DemoBoard = {
  id: string;
  name: string;
  type: DemoBoardType;
  projectKey: string;
};

export type BoardCreateInput = {
  name: string;
  type: Exclude<DemoBoardType, "simple">;
  projectKey: string;
};

export type BoardPersistence = {
  listBoards(): Promise<DemoBoard[]>;
  createBoard(input: BoardCreateInput): Promise<DemoBoard>;
  resetBoards(): Promise<DemoBoard[]>;
};

const seedBoard: DemoBoard = {
  id: "1",
  name: "KAN board",
  type: "simple",
  projectKey: "KAN",
};

let memoryBoards: DemoBoard[] = [{ ...seedBoard }];
let nextMemoryBoardId = 2;

const memoryPersistence: BoardPersistence = {
  async listBoards() {
    return memoryBoards.map((board) => ({ ...board }));
  },
  async createBoard(input) {
    const board: DemoBoard = { id: String(nextMemoryBoardId++), ...input };
    memoryBoards = [...memoryBoards, board];
    return { ...board };
  },
  async resetBoards() {
    resetMemoryBoards();
    return memoryBoards.map((board) => ({ ...board }));
  },
};

type Sql = NeonQueryFunction<false, false>;
type TransactionSql = NeonQueryFunctionInTransaction<false, false>;

type BoardRow = {
  board_number: number | string;
  name: string;
  type: DemoBoardType;
  project_key: string;
};

function rowToBoard(row: BoardRow): DemoBoard {
  return {
    id: String(row.board_number),
    name: row.name,
    type: row.type,
    projectKey: row.project_key,
  };
}

function setBoardSequenceQuery(sql: TransactionSql) {
  return sql`
    SELECT setval(
      pg_get_serial_sequence('jira_demo_boards', 'board_number'),
      COALESCE((SELECT MAX(board_number) FROM jira_demo_boards), 1),
      true
    )
  `;
}

export function createNeonBoardPersistence(sql: Sql): BoardPersistence {
  let ready: Promise<void> | undefined;

  async function ensureReady(): Promise<void> {
    if (!ready) {
      ready = sql
        .transaction((tx) => [
          tx`
            CREATE TABLE IF NOT EXISTS jira_demo_boards (
              board_number bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name text NOT NULL,
              type text NOT NULL CHECK (type IN ('kanban', 'scrum', 'simple')),
              project_key text NOT NULL,
              is_seed boolean NOT NULL DEFAULT false,
              created_at timestamptz NOT NULL DEFAULT now()
            )
          `,
          tx`
            INSERT INTO jira_demo_boards
              (board_number, name, type, project_key, is_seed)
            VALUES (1, ${seedBoard.name}, ${seedBoard.type}, ${seedBoard.projectKey}, true)
            ON CONFLICT (board_number) DO NOTHING
          `,
          setBoardSequenceQuery(tx),
        ])
        .then(() => undefined)
        .catch((error) => {
          ready = undefined;
          throw error;
        });
    }
    await ready;
  }

  return {
    async listBoards() {
      await ensureReady();
      const rows = await sql`
        SELECT board_number, name, type, project_key
        FROM jira_demo_boards
        ORDER BY board_number
      `;
      return (rows as unknown as BoardRow[]).map(rowToBoard);
    },
    async createBoard(input) {
      await ensureReady();
      const rows = await sql`
        INSERT INTO jira_demo_boards (name, type, project_key, is_seed)
        VALUES (${input.name}, ${input.type}, ${input.projectKey}, false)
        RETURNING board_number, name, type, project_key
      `;
      const row = rows[0] as BoardRow | undefined;
      if (!row) throw new Error("Neon did not return the created Jira board.");
      return rowToBoard(row);
    },
    async resetBoards() {
      await ensureReady();
      await sql.transaction((tx) => [
        tx`TRUNCATE TABLE jira_demo_boards RESTART IDENTITY`,
        tx`
          INSERT INTO jira_demo_boards
            (board_number, name, type, project_key, is_seed)
          VALUES (1, ${seedBoard.name}, ${seedBoard.type}, ${seedBoard.projectKey}, true)
        `,
        setBoardSequenceQuery(tx),
      ]);
      return [{ ...seedBoard }];
    },
  };
}

function databaseUrl(): string | undefined {
  const value = process.env.DATABASE_URL?.trim();
  return value === "" ? undefined : value;
}

function usesNeon(): boolean {
  const requested = process.env.JIRA_PERSISTENCE?.trim().toLowerCase();
  if (requested === "memory") return false;
  if (requested === "neon") return true;
  if (requested) {
    throw new Error(
      `JIRA_PERSISTENCE must be either "neon" or "memory"; received "${requested}".`,
    );
  }
  return databaseUrl() !== undefined;
}

let neonUrl: string | undefined;
let neonPersistence: BoardPersistence | undefined;

function getBoardPersistence(): BoardPersistence {
  if (!usesNeon()) return memoryPersistence;
  const url = databaseUrl();
  if (!url) {
    throw new Error(
      "Neon persistence requires DATABASE_URL. Set DATABASE_URL or use JIRA_PERSISTENCE=memory for the local fallback.",
    );
  }
  if (!neonPersistence || neonUrl !== url) {
    neonUrl = url;
    neonPersistence = createNeonBoardPersistence(neon(url));
  }
  return neonPersistence;
}

export async function listPersistentBoards(): Promise<DemoBoard[]> {
  return getBoardPersistence().listBoards();
}

export async function createPersistentBoard(
  input: BoardCreateInput,
): Promise<DemoBoard> {
  return getBoardPersistence().createBoard(input);
}

export async function resetPersistentBoards(): Promise<DemoBoard[]> {
  return getBoardPersistence().resetBoards();
}

/** Deterministic memory reset for protocol tests. */
export function resetMemoryBoards(): void {
  memoryBoards = [{ ...seedBoard }];
  nextMemoryBoardId = 2;
}
