<script setup lang="ts">
const props=defineProps<{title:string;brief:string}>();
interface Delivery {id:string;version:number;phase:string;cycle:number;sessionId?:string;childSessionId?:string;publication?:{number:number;url:string};review?:{verdict:string;summary:string};error?:string;history:unknown[]}
const route=useRoute();const router=useRouter();const run=ref<Delivery>();const error=ref('');const working=ref(false);const revision=ref('');let operationId:string|undefined;let timer:ReturnType<typeof setTimeout>|undefined;let disposed=false;
const stopped=new Set(['human_review','ready','blocked','needs_revision','cancelled']);
const cockpit=useCockpit();
async function remember(value:Delivery){try{const row=cockpit.items.value.runs.find(r=>r.id===value.id);await cockpit.save('runs',value.id,{label:props.title||'Delivery loop',station:'loop'},row?.version??0);}catch{/* Keep the authoritative delivery link even if its history index is unavailable. */}}
function schedule(){if(!disposed&&run.value&&!stopped.has(run.value.phase))timer=setTimeout(()=>void advance(),3000);}
async function start(){if(working.value)return;working.value=true;error.value='';operationId??=crypto.randomUUID();try{run.value=await $fetch<Delivery>('/factory/delivery',{method:'POST',body:{operationId,title:props.title,brief:props.brief},retry:0});await router.replace({query:{...route.query,delivery:run.value.id}});await remember(run.value);operationId=undefined;schedule();}catch{error.value='Could not confirm the loop start. Retry uses the same operation ID.';}finally{working.value=false;}}
async function advance(){if(!run.value||working.value)return;working.value=true;try{run.value=await $fetch<Delivery>(`/factory/delivery/${encodeURIComponent(run.value.id)}/advance`,{method:'POST',retry:0});error.value='';}catch{error.value='Could not refresh this delivery. Reconnect to the same run.';}finally{working.value=false;schedule();}}
async function resume(){if(!run.value||working.value)return;working.value=true;try{run.value=await $fetch<Delivery>(`/factory/delivery/${encodeURIComponent(run.value.id)}/resume`,{method:'POST',retry:0});error.value='';schedule();}catch{error.value='Could not resume this delivery. The existing operation is retained.';}finally{working.value=false;}}
async function cancel(){if(!run.value)return;clearTimeout(timer);try{run.value=await $fetch<Delivery>(`/factory/delivery/${encodeURIComponent(run.value.id)}/cancel`,{method:'POST',retry:0});}catch{error.value='Cancellation is unconfirmed. Reconnect to check the same run.';}}
async function revise(){if(!run.value||working.value)return;working.value=true;operationId??=crypto.randomUUID();try{run.value=await $fetch<Delivery>(`/factory/delivery/${encodeURIComponent(run.value.id)}/revise`,{method:'POST',body:{operationId,brief:revision.value},retry:0});operationId=undefined;revision.value='';error.value='';schedule();}catch{error.value='Could not confirm the revision. Your request is retained.';}finally{working.value=false;}}
watch(()=>route.query.delivery,async id=>{clearTimeout(timer);if(typeof id!=='string')return;try{run.value=await $fetch<Delivery>(`/factory/delivery/${encodeURIComponent(id)}`);schedule();}catch{error.value='Could not load this delivery. Keep its URL to retry.';}},{immediate:true});
onBeforeUnmount(()=>{disposed=true;clearTimeout(timer);});
</script>
<template><section class="panel" style="padding:24px;margin-top:24px"><div class="panel-heading"><h2>Build and review loop</h2><UBadge v-if="run">{{run.phase}}</UBadge></div><p class="muted">The worker creates a PR, an independent agent reviews it, and findings return to the branch owner. Merging stays manual.</p><UButton :disabled="!title.trim()||brief.trim().length<20||working" :loading="working" @click="start">Start delivery from this draft</UButton><p v-if="error" role="alert">{{error}}</p><template v-if="run"><p>Delivery {{run.id}} · revision {{run.cycle}}</p><p v-if="run.error">{{run.error}}</p><p v-if="run.review">{{run.review.summary}}</p><UButton v-if="run.publication" :to="run.publication.url" target="_blank">Open PR #{{run.publication.number}}</UButton><UButton v-if="run.phase==='blocked'" variant="outline" :disabled="working" @click="resume">Resume blocked observation</UButton><UButton v-else variant="outline" :disabled="working" @click="advance">Reconnect / advance</UButton><UButton v-if="!stopped.has(run.phase)" variant="ghost" @click="cancel">Stop delivery</UButton><template v-if="['ready','human_review','blocked','needs_revision'].includes(run.phase)"><UTextarea v-model="revision" placeholder="Describe the next revision for the branch owner"/><UButton :disabled="revision.trim().length<20||working" @click="revise">Request revision</UButton></template></template></section></template>
