-- Runtime bootstrap for the bounded Jira demo persistence layer.
-- The application runs this schema idempotently on the first Neon request.

CREATE TABLE IF NOT EXISTS jira_demo_issues (
  issue_number bigint GENERATED BY DEFAULT AS IDENTITY,
  key text GENERATED ALWAYS AS ('ADEO-' || issue_number::text) STORED PRIMARY KEY,
  title text NOT NULL,
  type text NOT NULL,
  status text NOT NULL,
  priority text NOT NULL,
  assignee text NOT NULL,
  description text NOT NULL,
  is_seed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (issue_number)
);

CREATE TABLE IF NOT EXISTS jira_demo_comments (
  comment_number bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_key text NOT NULL REFERENCES jira_demo_issues(key) ON DELETE CASCADE,
  body text NOT NULL,
  author text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS jira_demo_comments_issue_key_idx
  ON jira_demo_comments(issue_key, comment_number);
