import { test } from 'node:test';
import assert from 'node:assert/strict';
import { applyReview,newDelivery,operationFor,deliveryRequest,referenceState } from '../agent/lib/delivery-state.ts';
import { hostResult,eventsForDelivery,snapshotEvents } from '../agent/lib/delivery-events.ts';
import { validateJiraManifest,verificationCommands } from '../agent/lib/jira-policy.ts';
import { allowedWorkPath } from '../agent/lib/work-github.ts';
const task=deliveryRequest.parse({operationId:'11111111-1111-4111-8111-111111111111',title:'Jira state',brief:'Create a useful stateful issue list'});
function state(){const s=newDelivery('tester',task);s.publication={number:1,url:'https://github.com/example/pull/1',headSha:'a'.repeat(40),targetHeadSha:'b'.repeat(40),targetBranch:'main',ownerSessionId:'wrun_owner',branch:'factory/owner'};return s;}
const review={verdict:'approve',summary:'reviewed',headSha:'a'.repeat(40),baseSha:'b'.repeat(40),targetBranch:'main',findings:[],limitations:[]};
test('stable task IDs and phase operation IDs survive retries',()=>{assert.equal(state().id,state().id);assert.equal(operationFor(state().id,'review',1),operationFor(state().id,'review',1));assert.notEqual(operationFor(state().id,'review',1),operationFor(state().id,'review',2));});
test('review cannot advance a different head or target',()=>{for(const delta of [{headSha:'c'.repeat(40)},{baseSha:'c'.repeat(40)},{targetBranch:'other'}])assert.throws(()=>applyReview(state(),{...review,...delta}),/not bound/);});
test('missing browser evidence stops for human review',()=>{const s=state();applyReview(s,{...review,verdict:'incomplete',limitations:['Required host browser evidence missing']});assert.equal(s.phase,'human_review');});
test('blocking findings queue same-owner revision with stable operation, never a new worker',()=>{const s=state();applyReview(s,{...review,verdict:'changes_requested',findings:[{severity:'blocking',path:'apps/jira/app/app.vue',message:'Save fails',evidence:'reproduced'}]});assert.equal(s.phase,'revision_starting');assert.equal(s.publication?.ownerSessionId,'wrun_owner');assert.equal(s.cycle,1);});
test('model text and historical operation results cannot advance loop',()=>{assert.equal(hostResult([{type:'message.completed',data:{publication:{}}}],'publish_work','wrun_owner'),undefined);const e={type:'action.result',data:{status:'completed',result:{kind:'tool-result',toolName:'publish_work',output:{sessionId:'wrun_owner',operationId:'old'}}}};assert.equal(hostResult([e],'publish_work','wrun_owner','new'),undefined);assert.equal(hostResult([e],'publish_work','other'),undefined);assert.ok(hostResult([e],'publish_work','wrun_owner','old'));});
test('Jira manifest permits only semantic addition of exact test script',()=>{const before={name:'jira',scripts:{build:'nuxt build'},dependencies:{nuxt:'4.5.2'}};const after={...before,scripts:{...before.scripts,test:'node --test tests/*.test.ts'}};assert.doesNotThrow(()=>validateJiraManifest(JSON.stringify(before),JSON.stringify(after)));for(const candidate of [null,JSON.stringify({...after,dependencies:{nuxt:'other'}}),JSON.stringify({...after,scripts:{...after.scripts,test:'echo pass'}})])assert.throws(()=>validateJiraManifest(JSON.stringify(before),candidate));});
test('host policy opens Jira API/utils but keeps middleware/config protected and executes Jira tests',()=>{for(const path of ['apps/jira/server/api/issues.get.ts','apps/jira/server/utils/issues.ts','apps/jira/package.json'])assert.equal(allowedWorkPath(path),true);for(const path of ['apps/factory/server/api/a.ts','apps/jira/server/middleware/a.ts','apps/jira/server/api/../../bad.ts','apps/jira/nuxt.config.ts'])assert.equal(allowedWorkPath(path),false);assert.ok(verificationCommands(true).includes('pnpm --filter @jira-clone/jira test'));});

test('revision events use live Eve meta.deliveryIds and exclude the previous turn',()=>{const current={type:'turn.started',meta:{deliveryIds:['delivery-current']},data:{}};assert.deepEqual(eventsForDelivery([{type:'turn.completed',meta:{deliveryIds:['delivery-old']}},current],'delivery-current'),[current]);assert.deepEqual(eventsForDelivery([{type:'turn.started',deliveryIds:['delivery-current']}],'delivery-current'),[]);});
test('stale refs demand an explicit owner revision instead of a retry loop',()=>{const p=state().publication!;assert.equal(referenceState(p,{state:'open',headSha:p.headSha,targetBranch:p.targetBranch,targetHeadSha:'c'.repeat(40)}),'needs_revision');assert.equal(referenceState(p,{state:'closed',headSha:p.headSha,targetBranch:p.targetBranch,targetHeadSha:p.targetHeadSha}),'blocked');});
test('partial stream observations cannot produce trusted terminal evidence',async()=>{await assert.rejects(snapshotEvents({getStreamTailIndex:async()=>2,getEventStream:async()=>new ReadableStream({start(c){c.enqueue({type:'turn.completed'});c.close();}})} as never),/before captured tail/);});
